parameters:
#    application_annuaire.example.class: Application\AnnuaireBundle\Example

services:
#    application_annuaire.example:
#        class: %application_annuaire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
