services:
    sonata.admin.typecareer:
            class: Application\CareerBundle\Admin\TypeCareerAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Parcours", label: "Types de Parcours" }
            arguments:
                - ~
                - Application\CareerBundle\Entity\TypeCareer
                - ~
            calls:
                - [ setTranslationDomain, [ApplicationCareerBundle]]

    application_career.admin.career:
        class: Application\CareerBundle\Admin\CareerAdmin
        arguments: [~, Application\CareerBundle\Entity\Career, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Parcours", label: "Parcours" }
