application_career_homepage:
    path:     /career
    defaults: { _controller: ApplicationCareerBundle:Default:index }

application_career_new:
    path:     /career/new
    defaults: { _controller: ApplicationCareerBundle:Default:add }

application_career_edit:
    path:  /career/{id}/edit
    defaults: { _controller: "ApplicationCareerBundle:Default:edit" }
    requirements:
        id: \d*

application_career_delete:
    path:  /career/{id}/delete
    defaults: { _controller: "ApplicationCareerBundle:Default:delete" }
    requirements:
        id: \d*