imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    assets: ~


# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes:
            - 'AdminUserBundle:Form:fields.html.twig'
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%env(MYSQL_ADDON_HOST)%"
        port:     "%env(MYSQL_ADDON_PORT)%"
        dbname:   "%env(MYSQL_ADDON_DB)%"
        user:     "%env(MYSQL_ADDON_USER)%"
        password: "%env(MYSQL_ADDON_PASSWORD)%"
        charset:  UTF8
        logging:  true
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
          datetime_functions:
            date: DoctrineExtensions\Query\Mysql\Date
            strtodate: DoctrineExtensions\Query\Mysql\StrToDate


# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: ssl
    port: 465
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    #spool:     { type: memory }

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Admin\UserBundle\Entity\User
    registration:
        form:
            type: admin_user_registration
        confirmation:
            enabled:    false
            from_email:
                address:        mailing@anelis.org
                sender_name:    ANELIS
    resetting:
        email:
            from_email:
                address:        noreply@anelis.org
                sender_name:    ANELIS 
    change_password:
        form:
            type: Admin\UserBundle\Form\ChangePasswordFormType
            name: anelis_user_change_password

sonata_block:
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]
        # Your other blocks
sonata_admin:
    title:      Administration
    title_logo: assets/img/anelis-logo.png
    templates:
        layout: AdminUserBundle::standard_layout.html.twig

jms_payment_core:
    encryption:
        secret: def00000fcfa86e47e9945ba5e882e4cc3912f19d3053f404a2b893ef4133c5caed4a7c8c20e172fb0e84a7050ecf4033107af5f76b0b0eb64c4809c301227bfe353f094

jms_payment_paypal:
    username: "%env(PAYPAL_USERNAME)%"
    password: "%env(PAYPAL_PASSWORD)%"
    signature: "%env(PAYPAL_SIGNATURE)%"
    debug: false
    useraction: commit

#imports:
#    - { resource: @AdminUserBundle/Resources/config/admin.xml }
