services:
    sonata.admin.message:
        class: Application\ChatBundle\Admin\MessageAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tchat", label: "ZZ Chat" }
        arguments:
            - ~
            - Application\ChatBundle\Entity\Message
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationChatBundle]]