<?php

namespace Admin\UserBundle\Admin;

use Admin\UserBundle\Form\TelType;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Show\ShowMapper;

class UserAdmin extends AbstractAdmin
{
    /**
     * Used to avoid password change when editing an User.
     */
    public function preUpdate($object)
    {
        parent::preUpdate($object); // TODO: Change the autogenerated stub

        $plainPassword = $object->getPlainPassword();
        $user = $this->getConfigurationPool()->getContainer()->get('Doctrine')->getManager()->getRepository('Admin\UserBundle\Entity\User')->find($object->getId());
        if(empty($plainPassword)) //Si le champ password n'est pas rempli.
        {
            $object->setPassword($user->getPassword());
        }
    }
    // Fields to be shown on create/edit forms
    protected function configureFormFields(FormMapper $formMapper)
    {
        $roles = $this->getConfigurationPool()->getContainer()->getParameter('security.role_hierarchy.roles');
        $rolesChoices = self::flattenRoles($roles);

        $formMapper
            ->add('username', 'text', array('label' => 'Username',
                'required' => true))
            /**
             * Actually, living an empty field does not update the password while editing.
             * At user creation, it throws an error if the field is empty
             */
            ->add('plainpassword', 'password', array('label' => 'Mot de Passe* (Laissez vide pour ne pas le changer)',
                'required' => false))

            ->add('email', 'text', array('label' => 'Email',
                'required' => true))

            ->add('name', 'text', array('label' => 'Nom',
                'required' => true))

            ->add('surname', 'text', array('label' => 'Prénom',
                'required' => true))

            ->add('promotion', 'choice', array(
                'choices' => $this->lstPromotions(),
                'required' => true,
            ))

            ->add('filiere', 'choice', array(
                'choices' => array(
                    'F1' => 'F1',
                    'F2' => 'F2',
                    'F3' => 'F3',
                    'F4' => 'F4',
                    'F5' => 'F5',
                    'FI' => 'FI',
                    ),
                'required' => true
            ))

            ->add('birthday', 'birthday', array('label' => 'Date de naissance', 'required' => true))

            ->add('maritalName', 'text', array('label' => 'Nom Marital', 'required' => false))

            ->add('nickname', 'text', array('label' => 'Surnom', 'required' => false))

            ->add('address', 'text', array('label' => 'Adresse', 'required' => false))

            ->add('postalcode', 'text', array('label' => 'Code Postal', 'required' => false))

            ->add('city', 'text', array('label' => 'Ville', 'required' => false))

            ->add('country', 'text', array('label' => 'Pays', 'required' => false))

            ->add('telephone', TelType::class, array('label' => 'Numéro de Téléphone', 'required' => false))

            ->add('website', 'text', array('label' => 'Site Web', 'required' => false))

            ->add('socialFacebook', 'text', array('label' => 'Lien Facebook', 'required' => false))

            ->add('socialTwitter', 'text', array('label' => 'Lien Twitter', 'required' => false))

            ->add('socialGoogle', 'text', array('label' => 'Lien Google+', 'required' => false))

            ->add('socialYoutube', 'text', array('label' => 'Chaine Youtube', 'required' => false))

            ->add('socialInstagram', 'text', array('label' => 'Page Instagram', 'required' => false))

            ->add('biography', 'textarea', array('label' => 'Biographie', 'required' => false))

            ->add('maritalStatus', 'choice', array(
                'choices'   => array(
                    'Célibataire' => 'Célibataire',
                    'En couple' => 'En couple',
                    'Fiancé(e)' => 'Fiancé(e)',
                    'Marié(e)' => 'Marié(e)',
                    'En union libre' => 'En union libre',
                ),
                'required' => false
            ))

            ->add('childrenNumber', 'number', array('label' => 'Nombre d\'enfants', 'required' => false))

            ->add('roles', 'choice', array('choices' => $rolesChoices, 'multiple' => true, ))

        ;
    }

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        //TODO : Add french labels here
        $datagridMapper
            ->add('promotion')
            ->add('filiere')
            ->add('name')
            ->add('isEmailValid')
        ;
    }

    // Fields to be shown on lists
    protected function configureListFields(ListMapper $listMapper)
    {
        //TODO : Add french labels here
        $listMapper
            ->addIdentifier('name')
            ->addIdentifier('surname')
            ->add('promotion')
            ->add('filiere')
            ->add('email')
            ->add('city')
            ->add('telephone')
            // add custom action links
            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                )
            ))
        ;
    }

    protected function lstPromotions() {
        $result;

        for ($i = 1995 ; $i <= date('Y')+2 ; $i++) {
            $result["".$i] = $i;
        }
        return $result;
    }

    protected static function flattenRoles($rolesHierarchy)
    {
        $flatRoles = array();
        foreach($rolesHierarchy as $roles) {

            if(empty($roles)) {
                continue;
            }

            foreach($roles as $role) {
                if(!isset($flatRoles[$role])) {
                    $flatRoles[$role] = $role;
                }
            }
        }

        return $flatRoles;
    }

    protected function configureShowFields(ShowMapper $show)
    {
        $show
            ->add('username')

            ->add('email')

            ->add('name')

            ->add('surname')

            ->add('promotion')

            ->add('filiere')

            ->add('birthday')

            ->add('maritalName')

            ->add('nickname')

            ->add('address')

            ->add('postalcode')

            ->add('city')

            ->add('country')

            ->add('telephone')

            ->add('website')

            ->add('socialFacebook')

            ->add('socialTwitter')

            ->add('socialGoogle')

            ->add('socialYoutube')

            ->add('socialInstagram')

            ->add('biography')

            ->add('maritalStatus')

            ->add('childrenNumber')

            ->add('roles')
            ;
    }


}