<?php

namespace Admin\UserBundle\Entity;

use Application\AnnuaireBundle\Model\UserSearch;
use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

}
