services:
    sonata.admin.yearbook:
        class: Application\YearbookBundle\Admin\YearbookAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Yearbook", label: "Yearbook" }
        arguments:
            - ~
            - Application\YearbookBundle\Entity\Yearbook
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationYearbookBundle]]
    sonata.admin.yearbookmessages:
        class: Application\YearbookBundle\Admin\YearbookMessagesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Yearbook", label: "Yearbook Messages" }
        arguments:
            - ~
            - Application\YearbookBundle\Entity\YearbookMessages
            - ~
        calls:
            - [ setTranslationDomain, [ApplicationYearbookBundle]]