<?php

namespace Application\OffreBundle\Repository;

/**
 * OffreVarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreVarRepository extends \Doctrine\ORM\EntityRepository
{
}
