<?php

namespace Application\OffreBundle\Repository;

/**
 * UserOffreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOffreRepository extends \Doctrine\ORM\EntityRepository
{
}
