<?php

namespace Application\OffreBundle\Entity;

/**
 * OffersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffersRepository extends \Doctrine\ORM\EntityRepository
{
}
