application_cotisation_homepage:
    path:     /cotisation
    defaults: { _controller: ApplicationCotisationBundle:Cotisation:index }

application_cotisation_new:
    path:     /cotisation
    defaults: { _controller: ApplicationCotisationBundle:Cotisation:index }

application_cotisation_invoice_get:
    path:     /cotisation/invoice/{id}
    defaults: { _controller: ApplicationCotisationBundle:Invoice:get }
    requirements:
        id: \d*

application_cotisation_delete:
    path:  /cotisation/{id}/delete
    defaults: { _controller: "ApplicationCotisationBundle:Cotisation:delete" }
    requirements:
        id: \d*

application_cotisation_payer_paypal:
    path: /cotisation/{year}/pay
    defaults: { _controller: ApplicationCotisationBundle:Cotisation:createPayment }

application_cotisation_success_paypal:
    path: /cotisation/{year}/paypalOK
    defaults: { _controller: ApplicationCotisationBundle:Cotisation:paypalPaymentSuccess }

admin_cotisation_relancer:
    path:  /admin/cotisation/relancer/{id}
    defaults: { _controller: "ApplicationCotisationBundle:Cotisation:relancer" }
    requirements:
        id: \d*



