<?php

namespace Proxies\__CG__\Admin\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Newsletter extends \Admin\UserBundle\Entity\Newsletter implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'newsletter', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'commentaire', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'frequence', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'users'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'newsletter', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'commentaire', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'frequence', '' . "\0" . 'Admin\\UserBundle\\Entity\\Newsletter' . "\0" . 'users'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Newsletter $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setnewsletter($newsletter)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setnewsletter', [$newsletter]);

        return parent::setnewsletter($newsletter);
    }

    /**
     * {@inheritDoc}
     */
    public function getnewsletter()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getnewsletter', []);

        return parent::getnewsletter();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setcommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setcommentaire', [$commentaire]);

        return parent::setcommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getcommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getcommentaire', []);

        return parent::getcommentaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setfrequence($frequence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setfrequence', [$frequence]);

        return parent::setfrequence($frequence);
    }

    /**
     * {@inheritDoc}
     */
    public function getfrequence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getfrequence', []);

        return parent::getfrequence();
    }

    /**
     * {@inheritDoc}
     */
    public function adduser(\Admin\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'adduser', [$user]);

        return parent::adduser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsers($items)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsers', [$items]);

        return parent::setUsers($items);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsers', []);

        return parent::getUsers();
    }

}
